# Generated by Django 4.2.9 on 2026-03-26 20:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0003_remove_guest_guest_invitation_viewed_idx_and_more'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generatedmessage',
            name='ai_generate_event_i_5d6e7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='photoanalysis',
            name='ai_photo_an_event_i_7p8q9r_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_log_user_created_idx',
            old_name='ai_usage_lo_user_id_4f8b95_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_log_feature_created_idx',
            old_name='ai_usage_lo_feature_5e6a40_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_log_success_idx',
            old_name='ai_usage_lo_success_3f8c9a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_log_created_idx',
            old_name='ai_usage_lo_created_7d8e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedmessage',
            new_name='ai_msg_user_created_idx',
            old_name='ai_generate_user_id_2a1b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedmessage',
            new_name='ai_msg_style_idx',
            old_name='ai_generate_style_u_8g9h0i_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedmessage',
            new_name='ai_msg_created_idx',
            old_name='ai_generate_created_1j2k3l_idx',
        ),
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='ai_photo_user_created_idx',
            old_name='ai_photo_an_user_id_4m5n6o_idx',
        ),
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='ai_photo_created_idx',
            old_name='ai_photo_an_created_0s1t2u_idx',
        ),
        migrations.RemoveField(
            model_name='generatedmessage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='event',
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Associated order (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_messages', to='invitations.order'),
        ),
        migrations.AddField(
            model_name='photoanalysis',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Associated order (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_analyses', to='invitations.order'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was made'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the request failed'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature_type',
            field=models.CharField(choices=[('photo_analysis', 'Photo Analysis'), ('message_generation', 'Message Generation'), ('template_recommendation', 'Template Recommendation'), ('color_extraction', 'Color Extraction'), ('mood_detection', 'Mood Detection'), ('smart_suggestions', 'Smart Suggestions'), ('hashtag_generation', 'Hashtag Generation')], db_index=True, help_text='Type of AI feature used', max_length=30),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the usage log', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Request data sent to AI service'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Response data from AI service'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='success',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the AI request was successful'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens consumed'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(help_text='User who made the AI request', on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='context',
            field=models.JSONField(default=dict, help_text='Context data: bride_name, groom_name, date, venue, etc.'),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the message was generated'),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='generated_options',
            field=models.JSONField(default=list, help_text='Array of generated message options'),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the generated message', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='style_used',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('formal', 'Formal'), ('casual', 'Casual'), ('funny', 'Funny'), ('poetic', 'Poetic'), ('traditional', 'Traditional'), ('modern', 'Modern')], db_index=True, default='romantic', help_text='Style used for message generation', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens consumed for generation'),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='user',
            field=models.ForeignKey(help_text='User who generated the message', on_delete=django.db.models.deletion.CASCADE, related_name='generated_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the analysis was created'),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the photo analysis', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='image_url',
            field=models.URLField(help_text='URL of the analyzed image', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='mood',
            field=models.JSONField(blank=True, default=dict, help_text='Detected mood attributes (romantic, elegant, modern, etc.)'),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='primary_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted primary colors with hex codes and percentages'),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='style_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated style recommendations based on photo analysis'),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the analysis was last updated'),
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the photo', on_delete=django.db.models.deletion.CASCADE, related_name='photo_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user', 'success', '-created_at'], name='ai_log_user_success_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedmessage',
            index=models.Index(fields=['order', '-created_at'], name='ai_msg_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photoanalysis',
            index=models.Index(fields=['order', '-created_at'], name='ai_photo_order_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(check=models.Q(('tokens_used__gte', 0)), name='ai_log_nonnegative_tokens'),
        ),
        migrations.AddConstraint(
            model_name='photoanalysis',
            constraint=models.CheckConstraint(check=models.Q(('image_url', ''), _negated=True), name='ai_photo_nonempty_url'),
        ),
    ]
