# Generated by Django 4.2.9 on 2026-02-11 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Material-UI icon name', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Invitation Category',
                'verbose_name_plural': 'Invitation Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('regular_links', models.IntegerField(help_text='Number of regular invitation links')),
                ('test_links', models.IntegerField(default=5, help_text='Number of test links for demo')),
                ('price_inr', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees', max_digits=10)),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['sort_order', 'price_inr'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(help_text='Template preview image', upload_to='templates/thumbnails/')),
                ('animation_type', models.CharField(choices=[('elegant', 'Elegant'), ('fun', 'Fun & Playful'), ('traditional', 'Traditional'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('bollywood', 'Bollywood Style'), ('floral', 'Floral'), ('royal', 'Royal')], default='elegant', max_length=20)),
                ('animation_config', models.JSONField(default=dict, help_text='JSON configuration for animations')),
                ('theme_colors', models.JSONField(default=dict, help_text='JSON with primary, secondary, accent, background colors')),
                ('preview_url', models.URLField(blank=True)),
                ('supports_gallery', models.BooleanField(default=True)),
                ('supports_music', models.BooleanField(default=False)),
                ('supports_video', models.BooleanField(default=False)),
                ('supports_rsvp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='plans.invitationcategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
