# Generated by Django 4.2.9 on 2026-03-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitationcategory',
            name='category_active_sort_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitationcategory',
            name='category_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='plan_active_sort_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='plan_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_plan_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_plan_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_active_popular_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_premium_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_anim_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='template_active_idx',
        ),
    ]
