# Generated by Django 4.2.9 on 2026-03-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phoneverification',
            name='phone_ver_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneverification',
            name='phone_ver_user_used_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneverification',
            name='phone_ver_expires_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_phone_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_current_plan_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_blocked_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_active_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='activity_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='activity_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='activity_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='activity_type_created_idx',
        ),
    ]
