# Generated by Django 4.2.9 on 2026-02-11 20:37

import apps.invitations.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, default=apps.invitations.models.generate_slug, max_length=20, unique=True)),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('event_venue', models.TextField()),
                ('event_address', models.TextField(blank=True)),
                ('event_map_link', models.URLField(blank=True)),
                ('host_name', models.CharField(max_length=200)),
                ('host_phone', models.CharField(blank=True, max_length=15)),
                ('custom_message', models.TextField(blank=True)),
                ('banner_image', models.ImageField(help_text='Main banner image for the invitation', upload_to='invitations/banners/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Array of gallery image URLs (max 10)')),
                ('background_music', models.FileField(blank=True, null=True, upload_to='invitations/music/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('regular_links_used', models.IntegerField(default=0)),
                ('test_links_used', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_guests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_type_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_notes', models.TextField(blank=True)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('granted_regular_links', models.IntegerField(help_text='Number of regular links granted (can be modified by admin)')),
                ('granted_test_links', models.IntegerField(default=5, help_text='Number of test links granted')),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Invitation View Log',
                'verbose_name_plural': 'Invitation View Logs',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='invitations.order'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='plans.template'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField(blank=True)),
                ('attending', models.BooleanField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Unique device fingerprint hash', max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user_agent_hash', models.CharField(help_text='Hash of user agent string', max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('is_test_link', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['slug'], name='invitations_slug_717687_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['is_active', 'is_expired'], name='invitations_is_acti_7b0bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['invitation', 'device_fingerprint'], name='invitations_invitat_e263fe_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='invitations_ip_addr_271078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('invitation', 'device_fingerprint')},
        ),
    ]
