# Generated by Django 4.2.9 on 2026-03-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_invitation_viewed_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_invitation_attending_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_attending_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_user_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_active_expires_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitation_template_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitationviewlog',
            name='viewlog_invitation_viewed_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitationviewlog',
            name='viewlog_viewed_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitationviewlog',
            name='viewlog_ip_viewed_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_approved_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_status_created_idx',
        ),
    ]
